<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>.infuse</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*\*|\{\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*\*/|^\s*\}</string>
	<key>name</key>
	<string>Infuse</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(slide|author|company|title|subtitle|copyright|transition|background|format|notes)\b</string>
			<key>name</key>
			<string>keyword.control.untitled</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.untitled</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.untitled</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>text.html.textile</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.html.textile.infuse</string>
	<key>uuid</key>
	<string>58106E06-EF6C-4D3C-96BE-828875F29B93</string>
</dict>
</plist>
